name: flutter_bloc
description: Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 6.0.6
repository: https://github.com/felangel/bloc/tree/master/packages/flutter_bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/#/gettingstarted

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../bloc
  provider:
    path: ../provider

dev_dependencies:
  flutter_test:
    sdk: flutter
